name: 'aks-cluster-create-$(Build.BuildId)'

variables:
- group: aks-cluster

trigger: none
pr: none
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  name: validate
  inputs:
    targetType: inline
    script: ls -la
- task: DownloadSecureFile@1
  name: certificate
  inputs:
    secureFile: 'id_rsa.pub'
- task: AzureCLI@2
  name: deploy
  inputs:
    azureSubscription: 'Azure-vsenterprise'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cert=`cat $(certificate.secureFilePath)` && echo $cert && \
      az deployment sub create \
      --template-file patterns/aks-cluster.pattern.bicep \
      --location $(location) \
      --parameters resourceGroupName=$(resourceGroupName) location=$(location) linuxAdminUsername=$(linuxAdminUsername) sshRSAPublicKey="$cert"
    addSpnToEnvironment: true
