name: 'blob-storage-create-$(Build.BuildId)-$(Build.SourceBranchName)-$(Date:yyyyMMdd.HHmmss)'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-vsenterprise'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --template-file azure-biceps-collection/pipelines/blob-storage.yml
    addSpnToEnvironment: true
