name: 'blob-storage-create-$(Build.BuildId)-$(Build.SourceBranchName)-$(Date:yyyyMMdd.HHmmss)'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  name: validate
  inputs:
    targetType: inline
    script: ls -la
- task: AzureCLI@2
  name: deploy
  inputs:
    azureSubscription: 'Azure-vsenterprise'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --template-file pipelines/blob-storage.yml --location eastus
    addSpnToEnvironment: true
