name: 'storage-blob-create-$(Build.BuildId)'

variables:
- group: storage-blob

trigger: none
pr: none
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  name: validate
  inputs:
    targetType: inline
    script: ls -la
- task: AzureCLI@2
  name: deploy
  inputs:
    azureSubscription: 'Azure-vsenterprise'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create \
      --template-file core/storage-blob.main.bicep \
      --location $(location) \
      --parameters resourceGroupName=$(resourceGroupName)
    addSpnToEnvironment: true
